### ISSUE TITLE
eleventy

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/spruce-reporter#1]
@adamlaki Szerintem nem kell egy textarea-hoz eleventy.

**Comment by adamlaki** [comment]
@szepeviktor szerintem sem, ez egy index.html pár elemmel. Viszont a starterből pár dolog hasznos. Letakarítsam ez (dobjam ki 11ty-t), vagy csinálsz egy új repót, hogy lekerüljön róla a "generated from"?

**Comment by adamlaki** [comment]
Viszont aztán az eleventy a legvégén nem biztos hogy útban van, inkább csak túlzás.

**Comment by szepeviktor** [comment]
Töröljük csak le az eleventy-t.
A végén az az index.html élég.

**Comment by szepeviktor** [comment]
Majd GitHub Pages-en fogjuk host-olni, illetve belemásoljuk olyan projektekbe, ahol hasznát lehet venni. `example.com/browser-reporter/`

**Comment by adamlaki** [comment]
@szepeviktor ragaszkodsz a textareahoz?

**Comment by szepeviktor** [comment]
Nem!

**Comment by adamlaki** [comment]
Rendben, akkor szeparálom, szerintem egyszerűbb lesz.

**Comment by szepeviktor** [comment]
Csak legyen karaktere, amikor megjelenik a dobozka.
Föl lehessen ismerni, hogy _Á! Ez az!_

**Comment by adamlaki** [comment]
![image](https://github.com/szepeviktor/spruce-reporter/assets/5145299/d816555c-b5f4-487d-b14d-a8304c854761)

Ilyen nagyon minimálra hagynám, mivel egy tisztán utility. Kiteszed valahova, hogy élesben is lásd? 

Dark mode megy, meg meg az alapfunkcionalitás is.

**Comment by adamlaki** [comment]
Nem használtam mono fontot. Ragaszkodsz hozzá?

**Comment by adamlaki** [comment]
Valamint a Spruce színei és favikonja van rajta. Nem tudom hogy mit tervezel - vagy tervezel-e - helyettük.

**Comment by szepeviktor** [comment]
Minden megfelelő.

**Comment by szepeviktor** [comment]
Köszönöm.

Melyik csomagoló tud olyat, hogy a HTML önhordó legyen, ne kelljen hozzá plusz HTTP kérés.

**Comment by adamlaki** [comment]
Tehát hogy minden külső assestet (CSS, JS) ágyazzon be a HTML-be? Eleventy-vel tudtuk volna ezt egyszerűen kezelni. Mást nem ismerek, de biztos van balami npm csomag, ami használható erre.
